// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSDv7YttsMs_G2dHP-y7IXs2VCVnL2OEY',
    appId: '1:433382468188:web:959148df4c2fad07c05499',
    messagingSenderId: '433382468188',
    projectId: 'kosmetrics-cb21b',
    authDomain: 'kosmetrics-cb21b.firebaseapp.com',
    databaseURL: 'https://kosmetrics-cb21b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kosmetrics-cb21b.firebasestorage.app',
    measurementId: 'G-83Z3MS8GZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiayLaRC1HBVX5Tw0BdDAiE4QaroanOz0',
    appId: '1:433382468188:android:3c31397e98b46c08c05499',
    messagingSenderId: '433382468188',
    projectId: 'kosmetrics-cb21b',
    databaseURL: 'https://kosmetrics-cb21b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kosmetrics-cb21b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjazW8KGU92sqxSOp8AXhELVdAhgx3kzg',
    appId: '1:433382468188:ios:e9136ef3e5dd2c94c05499',
    messagingSenderId: '433382468188',
    projectId: 'kosmetrics-cb21b',
    databaseURL: 'https://kosmetrics-cb21b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kosmetrics-cb21b.firebasestorage.app',
    iosBundleId: 'com.example.kosmetric',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjazW8KGU92sqxSOp8AXhELVdAhgx3kzg',
    appId: '1:433382468188:ios:e9136ef3e5dd2c94c05499',
    messagingSenderId: '433382468188',
    projectId: 'kosmetrics-cb21b',
    databaseURL: 'https://kosmetrics-cb21b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kosmetrics-cb21b.firebasestorage.app',
    iosBundleId: 'com.example.kosmetric',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSDv7YttsMs_G2dHP-y7IXs2VCVnL2OEY',
    appId: '1:433382468188:web:fd557502577f9422c05499',
    messagingSenderId: '433382468188',
    projectId: 'kosmetrics-cb21b',
    authDomain: 'kosmetrics-cb21b.firebaseapp.com',
    databaseURL: 'https://kosmetrics-cb21b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kosmetrics-cb21b.firebasestorage.app',
    measurementId: 'G-4PB0J9B12Y',
  );
}
